name: Deploy index.html to AWS EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set permissions on /var/www/html
        run: |
          ssh -i "${{ secrets.PRIVATE_KEY }}" ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo chown -R ubuntu:ubuntu /var/www/html"
          ssh -i "${{ secrets.PRIVATE_KEY }}" ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo chmod -R 755 /var/www/html"

      - name: Deploy index.html to EC2 instance
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ubuntu
          SOURCE: index.html
          TARGET: /var/www/html
