name: Deploy index.html to AWS EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy index.html to EC2 instance
        uses: easingthemes/ssh-deploy@main # https://github.com/marketplace/actions/ssh-deploy
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ubuntu
          SOURCE: index.html
          TARGET: /var/www/html  # Update to the default document root of your Nginx server
